name: PR Validation

# Run on pull requests to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Install project dependencies
      - name: Install dependencies
        run: npm install
      
      # Build Project
      - name: Build Project
        run: npm run build

      # Add a success message
      - name: Build successful
        run: echo "✅ Build completed successfully! The PR can be merged safely."
